// Generated by re2zig 4.3.1 on Mon Jan 26 13:55:55 2026
// re2zig $INPUT -o $OUTPUT

// https://conservatory.scheme.org/schemers/Documents/Standards/R5RS/HTML/r5rs-Z-H-10.html#%_sec_7.1.1
const std = @import("std");

pub const LexerError = error{ UnclosedString, UnknownToken };
pub const Token = struct {
    id: Id,
    start: usize,
    end: usize,


    pub const Id = enum {
        invalid,
        lparen,
        rparen,
        identifier,
        boolean,
        intNumber,
        floatNumber,
        string,
        character,
        vector,
        eof,
        quote,
        quasiquote,
        unquote,
        unquote_splicing,
        syntax,
        quasisyntax,
        unsyntax,
        unsyntax_splicing,
    };

    pub fn slice(self: Token, buff: [] const u8) []const u8 {
        return buff[self.start..self.end];
    }
};

pub const Lexer = struct {
    yyinput: [:0]const u8,
    yycursor: usize = 0,
    yymarker: usize = 0,
    yylimit: usize,

    pub fn init(text: [:0]const u8) Lexer {
        return .{ .yyinput = text, .yylimit = text.len };
    }

    pub fn nextToken(self:*Lexer) LexerError!Token {
       return _nextToken(self);
    }
};
pub fn _nextToken(yyrecord: *Lexer) LexerError!Token {
   loop: while(true) {
      const start = yyrecord.yycursor;
        
    var yych: u8 = 0;
    var yyaccept: u32 = 0;
    var yystate: u32 = 0;
    yyl: while (true) {
        switch (yystate) {
            0 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x09...0x0A,
                    0x0D,
                    0x20 => {
                        yyrecord.yycursor += 1;
                        yystate = 3;
                        continue :yyl;
                    },
                    0x21,
                    0x24...0x26,
                    0x2A,
                    0x2F,
                    0x3A,
                    0x3C...0x3F,
                    0x41...0x5A,
                    0x5E...0x5F,
                    0x61...0x7A,
                    0x7E => {
                        yyrecord.yycursor += 1;
                        yystate = 5;
                        continue :yyl;
                    },
                    0x22 => {
                        yyrecord.yycursor += 1;
                        yystate = 7;
                        continue :yyl;
                    },
                    0x23 => {
                        yyrecord.yycursor += 1;
                        yystate = 9;
                        continue :yyl;
                    },
                    0x27 => {
                        yyrecord.yycursor += 1;
                        yystate = 10;
                        continue :yyl;
                    },
                    0x28 => {
                        yyrecord.yycursor += 1;
                        yystate = 11;
                        continue :yyl;
                    },
                    0x29 => {
                        yyrecord.yycursor += 1;
                        yystate = 12;
                        continue :yyl;
                    },
                    0x2B => {
                        yyrecord.yycursor += 1;
                        yystate = 13;
                        continue :yyl;
                    },
                    0x2C => {
                        yyrecord.yycursor += 1;
                        yystate = 14;
                        continue :yyl;
                    },
                    0x2D => {
                        yyrecord.yycursor += 1;
                        yystate = 16;
                        continue :yyl;
                    },
                    0x2E => {
                        yyrecord.yycursor += 1;
                        yystate = 17;
                        continue :yyl;
                    },
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 19;
                        continue :yyl;
                    },
                    0x3B => {
                        yyrecord.yycursor += 1;
                        yystate = 21;
                        continue :yyl;
                    },
                    0x5B => {
                        yyrecord.yycursor += 1;
                        yystate = 23;
                        continue :yyl;
                    },
                    0x5D => {
                        yyrecord.yycursor += 1;
                        yystate = 24;
                        continue :yyl;
                    },
                    0x60 => {
                        yyrecord.yycursor += 1;
                        yystate = 25;
                        continue :yyl;
                    },
                    else => {
                        if (yyrecord.yylimit <= yyrecord.yycursor) {
                            yystate = 62;
                            continue :yyl;
                        }
                        yyrecord.yycursor += 1;
                        yystate = 1;
                        continue :yyl;
                    },
                }
            },
            1 => {
                yystate = 2;
                continue :yyl;
            },
            2 => { std.debug.print("unknown token: '{s}'", .{yyrecord.yyinput[start..yyrecord.yycursor]}); return error.UnknownToken; },
            3 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x09...0x0A,
                    0x0D,
                    0x20 => {
                        yyrecord.yycursor += 1;
                        yystate = 3;
                        continue :yyl;
                    },
                    else => {
                        yystate = 4;
                        continue :yyl;
                    },
                }
            },
            4 => { continue :loop; },
            5 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x21,
                    0x24...0x26,
                    0x2A...0x2B,
                    0x2D...0x3A,
                    0x3C...0x5A,
                    0x5E...0x5F,
                    0x61...0x7A,
                    0x7E => {
                        yyrecord.yycursor += 1;
                        yystate = 5;
                        continue :yyl;
                    },
                    else => {
                        yystate = 6;
                        continue :yyl;
                    },
                }
            },
            6 => { return .{ .id = .identifier, .start = start, .end = yyrecord.yycursor}; },
            7 => {
                yyaccept = 0;
                yyrecord.yymarker = yyrecord.yycursor;
                yych = yyrecord.yyinput[yyrecord.yycursor];
                if (yych <= 0x00) {
                    if (yyrecord.yylimit <= yyrecord.yycursor) {
                        yystate = 8;
                        continue :yyl;
                    }
                    yyrecord.yycursor += 1;
                    yystate = 26;
                    continue :yyl;
                }
                yystate = 27;
                continue :yyl;
            },
            8 => { return error.UnclosedString; },
            9 => {
                yyaccept = 1;
                yyrecord.yymarker = yyrecord.yycursor;
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x27 => {
                        yyrecord.yycursor += 1;
                        yystate = 30;
                        continue :yyl;
                    },
                    0x28 => {
                        yyrecord.yycursor += 1;
                        yystate = 31;
                        continue :yyl;
                    },
                    0x2C => {
                        yyrecord.yycursor += 1;
                        yystate = 32;
                        continue :yyl;
                    },
                    0x5C => {
                        yyrecord.yycursor += 1;
                        yystate = 34;
                        continue :yyl;
                    },
                    0x60 => {
                        yyrecord.yycursor += 1;
                        yystate = 36;
                        continue :yyl;
                    },
                    0x66 => {
                        yyrecord.yycursor += 1;
                        yystate = 37;
                        continue :yyl;
                    },
                    0x74 => {
                        yyrecord.yycursor += 1;
                        yystate = 38;
                        continue :yyl;
                    },
                    else => {
                        yystate = 2;
                        continue :yyl;
                    },
                }
            },
            10 => { return .{ .id = .quote,   .start = start, .end = yyrecord.yycursor}; },
            11 => { return .{ .id = .lparen, .start = start, .end = yyrecord.yycursor}; },
            12 => { return .{ .id = .rparen, .start = start, .end = yyrecord.yycursor}; },
            13 => {
                yystate = 6;
                continue :yyl;
            },
            14 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x40 => {
                        yyrecord.yycursor += 1;
                        yystate = 39;
                        continue :yyl;
                    },
                    else => {
                        yystate = 15;
                        continue :yyl;
                    },
                }
            },
            15 => { return .{ .id = .unquote,   .start = start, .end = yyrecord.yycursor}; },
            16 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 40;
                        continue :yyl;
                    },
                    else => {
                        yystate = 6;
                        continue :yyl;
                    },
                }
            },
            17 => {
                yyaccept = 2;
                yyrecord.yymarker = yyrecord.yycursor;
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x2E => {
                        yyrecord.yycursor += 1;
                        yystate = 41;
                        continue :yyl;
                    },
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 42;
                        continue :yyl;
                    },
                    else => {
                        yystate = 18;
                        continue :yyl;
                    },
                }
            },
            18 => { return .{ .id = .identifier, .start = start, .end = yyrecord.yycursor}; },
            19 => {
                yyaccept = 3;
                yyrecord.yymarker = yyrecord.yycursor;
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x2E => {
                        yyrecord.yycursor += 1;
                        yystate = 42;
                        continue :yyl;
                    },
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 19;
                        continue :yyl;
                    },
                    0x45,
                    0x65 => {
                        yyrecord.yycursor += 1;
                        yystate = 44;
                        continue :yyl;
                    },
                    else => {
                        yystate = 20;
                        continue :yyl;
                    },
                }
            },
            20 => { return .{ .id = .intNumber, .start = start, .end = yyrecord.yycursor}; },
            21 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x0A => {
                        yystate = 22;
                        continue :yyl;
                    },
                    else => {
                        if (yyrecord.yylimit <= yyrecord.yycursor) {
                            yystate = 22;
                            continue :yyl;
                        }
                        yyrecord.yycursor += 1;
                        yystate = 21;
                        continue :yyl;
                    },
                }
            },
            22 => { continue :loop; },
            23 => { return .{ .id = .lparen, .start = start, .end = yyrecord.yycursor}; },
            24 => { return .{ .id = .rparen, .start = start, .end = yyrecord.yycursor}; },
            25 => { return .{ .id = .quasiquote, .start = start, .end = yyrecord.yycursor}; },
            26 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                yystate = 27;
                continue :yyl;
            },
            27 => {
                switch (yych) {
                    0x22 => {
                        yyrecord.yycursor += 1;
                        yystate = 28;
                        continue :yyl;
                    },
                    0x5C => {
                        yyrecord.yycursor += 1;
                        yystate = 29;
                        continue :yyl;
                    },
                    else => {
                        if (yyrecord.yylimit <= yyrecord.yycursor) {
                            yystate = 35;
                            continue :yyl;
                        }
                        yyrecord.yycursor += 1;
                        yystate = 26;
                        continue :yyl;
                    },
                }
            },
            28 => { return .{ .id = .string, .start = start, .end = yyrecord.yycursor}; },
            29 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                if (yych <= 0x00) {
                    if (yyrecord.yylimit <= yyrecord.yycursor) {
                        yystate = 35;
                        continue :yyl;
                    }
                    yyrecord.yycursor += 1;
                    yystate = 26;
                    continue :yyl;
                }
                yyrecord.yycursor += 1;
                yystate = 26;
                continue :yyl;
            },
            30 => { return .{ .id = .syntax,   .start = start, .end = yyrecord.yycursor}; },
            31 => {
                yyrecord.yycursor -= 1;
                return .{ .id = .vector, .start = start, .end = yyrecord.yycursor};
            },
            32 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x40 => {
                        yyrecord.yycursor += 1;
                        yystate = 45;
                        continue :yyl;
                    },
                    else => {
                        yystate = 33;
                        continue :yyl;
                    },
                }
            },
            33 => { return .{ .id = .unsyntax,   .start = start, .end = yyrecord.yycursor}; },
            34 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x0A => {
                        yystate = 35;
                        continue :yyl;
                    },
                    0x6E => {
                        yyrecord.yycursor += 1;
                        yystate = 48;
                        continue :yyl;
                    },
                    0x73 => {
                        yyrecord.yycursor += 1;
                        yystate = 49;
                        continue :yyl;
                    },
                    else => {
                        if (yyrecord.yylimit <= yyrecord.yycursor) {
                            yystate = 35;
                            continue :yyl;
                        }
                        yyrecord.yycursor += 1;
                        yystate = 46;
                        continue :yyl;
                    },
                }
            },
            35 => {
                yyrecord.yycursor = yyrecord.yymarker;
                switch (yyaccept) {
                    0 => {
                        yystate = 8;
                        continue :yyl;
                    },
                    1 => {
                        yystate = 2;
                        continue :yyl;
                    },
                    2 => {
                        yystate = 18;
                        continue :yyl;
                    },
                    3 => {
                        yystate = 20;
                        continue :yyl;
                    },
                    4 => {
                        yystate = 43;
                        continue :yyl;
                    },
                    else => {
                        yystate = 47;
                        continue :yyl;
                    },
                }
            },
            36 => { return .{ .id = .quasisyntax,   .start = start, .end = yyrecord.yycursor}; },
            37 => { return .{ .id = .boolean, .start = start, .end = yyrecord.yycursor}; },
            38 => { return .{ .id = .boolean,  .start = start, .end = yyrecord.yycursor}; },
            39 => { return .{ .id = .unquote_splicing,   .start = start, .end = yyrecord.yycursor}; },
            40 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 40;
                        continue :yyl;
                    },
                    else => {
                        yystate = 20;
                        continue :yyl;
                    },
                }
            },
            41 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x2E => {
                        yyrecord.yycursor += 1;
                        yystate = 13;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            42 => {
                yyaccept = 4;
                yyrecord.yymarker = yyrecord.yycursor;
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 42;
                        continue :yyl;
                    },
                    0x45,
                    0x65 => {
                        yyrecord.yycursor += 1;
                        yystate = 44;
                        continue :yyl;
                    },
                    else => {
                        yystate = 43;
                        continue :yyl;
                    },
                }
            },
            43 => { return .{ .id = .floatNumber, .start = start, .end = yyrecord.yycursor}; },
            44 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x2B,
                    0x2D => {
                        yyrecord.yycursor += 1;
                        yystate = 50;
                        continue :yyl;
                    },
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 51;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            45 => { return .{ .id = .unsyntax_splicing,   .start = start, .end = yyrecord.yycursor}; },
            46 => {
                yystate = 47;
                continue :yyl;
            },
            47 => { return .{ .id = .character, .start = start, .end = yyrecord.yycursor}; },
            48 => {
                yyaccept = 5;
                yyrecord.yymarker = yyrecord.yycursor;
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x65 => {
                        yyrecord.yycursor += 1;
                        yystate = 52;
                        continue :yyl;
                    },
                    else => {
                        yystate = 47;
                        continue :yyl;
                    },
                }
            },
            49 => {
                yyaccept = 5;
                yyrecord.yymarker = yyrecord.yycursor;
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x70 => {
                        yyrecord.yycursor += 1;
                        yystate = 53;
                        continue :yyl;
                    },
                    else => {
                        yystate = 47;
                        continue :yyl;
                    },
                }
            },
            50 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 51;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            51 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x30...0x39 => {
                        yyrecord.yycursor += 1;
                        yystate = 51;
                        continue :yyl;
                    },
                    else => {
                        yystate = 43;
                        continue :yyl;
                    },
                }
            },
            52 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x77 => {
                        yyrecord.yycursor += 1;
                        yystate = 54;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            53 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x61 => {
                        yyrecord.yycursor += 1;
                        yystate = 55;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            54 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x6C => {
                        yyrecord.yycursor += 1;
                        yystate = 56;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            55 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x63 => {
                        yyrecord.yycursor += 1;
                        yystate = 57;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            56 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x69 => {
                        yyrecord.yycursor += 1;
                        yystate = 58;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            57 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x65 => {
                        yyrecord.yycursor += 1;
                        yystate = 59;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            58 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x6E => {
                        yyrecord.yycursor += 1;
                        yystate = 60;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            59 => { return .{ .id = .character, .start = start, .end = yyrecord.yycursor}; },
            60 => {
                yych = yyrecord.yyinput[yyrecord.yycursor];
                switch (yych) {
                    0x65 => {
                        yyrecord.yycursor += 1;
                        yystate = 61;
                        continue :yyl;
                    },
                    else => {
                        yystate = 35;
                        continue :yyl;
                    },
                }
            },
            61 => { return .{ .id = .character, .start = start, .end = yyrecord.yycursor}; },
            62 => { return .{ .id = .eof, .start = start, .end = yyrecord.yycursor}; },
            else => { @panic("internal lexer error"); },
        }
    }

    }
}

pub fn main() !void {
    const text =
          \\123 foo "foo bar" "foo \t \" bar" ; foo bar
          \\ #( 1456 ()) #t #f 123.456 ... a+ b-
          \\ #\z #\space #\newline (+ . ) let* set! unquote-splicing
          ;
    //var st : State = .{ .yyinput = text, .yylimit = text.len };
    var lexer = Lexer.init(text);
    var t: Token = lexer.nextToken();
    while (t.id != .eof) {
       std.debug.print("token: {any} {s}\n", .{t.id, t.slice(text)});
       t = lexer.nextToken();
    }
}
